In [174]:
import numpy as np
import random
import scipy.stats as sps

In [ ]:
np.lookfor('mean value of array') 

#### Task 1
- Создать массив чисел от -4pi до 4pi , количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива
- С помощью np.all проверить, что все элементы равны единице.

In [91]:
x = np.linspace(-4*np.pi, 4*np.pi, 100)
print(f"Array : \n{x}")

Array : 
[-12.56637061 -12.31250454 -12.05863847 -11.8047724  -11.55090632
 -11.29704025 -11.04317418 -10.7893081  -10.53544203 -10.28157596
 -10.02770988  -9.77384381  -9.51997774  -9.26611167  -9.01224559
  -8.75837952  -8.50451345  -8.25064737  -7.9967813   -7.74291523
  -7.48904915  -7.23518308  -6.98131701  -6.72745093  -6.47358486
  -6.21971879  -5.96585272  -5.71198664  -5.45812057  -5.2042545
  -4.95038842  -4.69652235  -4.44265628  -4.1887902   -3.93492413
  -3.68105806  -3.42719199  -3.17332591  -2.91945984  -2.66559377
  -2.41172769  -2.15786162  -1.90399555  -1.65012947  -1.3962634
  -1.14239733  -0.88853126  -0.63466518  -0.38079911  -0.12693304
   0.12693304   0.38079911   0.63466518   0.88853126   1.14239733
   1.3962634    1.65012947   1.90399555   2.15786162   2.41172769
   2.66559377   2.91945984   3.17332591   3.42719199   3.68105806
   3.93492413   4.1887902    4.44265628   4.69652235   4.95038842
   5.2042545    5.45812057   5.71198664   5.96585272   6.21971879
   

In [92]:
np.all((np.sin(x)**2 + np.cos(x)**2).round() == 1)

True

In [97]:
out = np.sin(x)**2 + np.cos(x)**2
print(f"Out: \n{out}")

Out: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### -----------

In [116]:
b = np.arange(0, 20)
b.shape = (2, 10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [117]:
print(b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [120]:
c = np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Task 2
Создать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0.

In [130]:
arr = -1*np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))
print(arr)

[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


#### Task 3
Отобразить вектор размера 100, в котором вычеркивается x, если x --- составное (т. е. не является простым)

In [147]:
arr = np.ones(100, dtype=bool)

In [148]:
arr[:2] = False

In [149]:
N_max = int(np.sqrt(len(arr)))
for i in range(2, N_max):
    arr[2*i::i] = False # начинаем с 2i с шагом i
    
print(arr)

[False False  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False False False False  True False False False  True
 False  True False False False False False  True False False False  True
 False False False False False  True False False False False False False
 False  True False False]


#### Tensors

In [150]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [151]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

# суммируем сразу по двум осям, то есть для фиксированной i 
# суммируем только элементы с индексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


In [173]:
matrix = np.arange(12).reshape(3,4)
#print(f"Det = {X}")

In [158]:
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Task 4

In [380]:
a = np.random.sample((2, 2))
b = np.random.sample((2, 2))
print("First matrix: \n",a)
print("\nSecond matrix: \n",b)
print("\nLast matrix row: \n\n",a[-1::])

First matrix: 
 [[0.70637555 0.16761483]
 [0.41146643 0.76855982]]

Second matrix: 
 [[0.00520456 0.91950441]
 [0.87468441 0.4722944 ]]

Last matrix row: 

 [[0.41146643 0.76855982]]


In [381]:
print(a.shape)
print(b.shape)

(2, 2)
(2, 2)


In [382]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
def mult(a,b):    
    if len(a[0]) == len(b): 
        result = [] 
        for i in range(0,len(a)): 
            temp = [] 
        
            for j in range(0,len(b[0])): 
                total = 0 
                l = 0 
                for k in range(0,len(A[0])):
                    total += a[i][k]*b[l][j]
                    l = l+1
                temp.append(total)
            result.append(temp)                
        return result
    else:
        return (print("not possible"))
print(mult(a,b))

[[19, 22], [43, 50]]


In [383]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 11 µs, sys: 0 ns, total: 11 µs
Wall time: 14.1 µs


In [384]:
def np_mult(a, b):
    ccc = np.dot(a,b)
    #pass
np_mult(a,b)

In [385]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 35 µs, sys: 6 µs, total: 41 µs
Wall time: 43.9 µs
